### ISSUE TITLE
Clean up repository structure

### ISSUE THREAD

**Issue by TorstenStueber** [pendulum-chain/pendulum-solidity-wrapper#38]
In view of https://github.com/pendulum-chain/pendulum-ink-wrapper/issues/1#issuecomment-1863207654 we should:
* rename this repository (not mentioning ink anymore)
* clean up the content, e.g., remove `price_feed` and `psp_pendulum` folders (they can go to a different branch for example or we remove them entirely)
* also check whether the `docs` folder needs to be updated

**Comment by TorstenStueber** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/pendulum-ink-wrapper/38?planning-poker) with Zenhub @b-yap @bogdanS98 @ebma @gianfra-t @TorstenStueber

**Comment by gianfra-t** [comment]
Just to be sure, `price_feed` has been replaced by `PriceOracleWrapper.sol` while `psp_pendulum` was replaced by `ERC20Wrapper.sol` right?

**Comment by ebma** [comment]
Yes 👍
